### PR TITLE
Fix the contrast gui (fixes #109)

### LINKED ISSUE #109: Is Contrast  popup gone?
can't have access contrast menu on gray images
what's happen with gui contrast?
This - _"Finally, for grayscale images, right-clicking on the image yields a brightness/contrast GUI:"_ does not work.

### PR DESCRIPTION
**Pull request by timholy**

### CODE REVIEW

**Comment by postoroniy** [comment]
I merged with clamp branch and tested in thi s way
```
using ImageView,Images
x=rand(Int16,128,128)
imshow(x)
```
after right click on image and choosing contrast got this
ERROR: invalid Array dimensions
 in hist at ./deprecated.jl:644 [inlined]
 in prepare_histogram(::Array{Int16,2}, ::Int64, ::Int16, ::Int16) at /home/slava/.julia/v0.5/ImageView/src/contrast.jl:190
 in contrastgui(::Tk.Tk_Toplevel, ::SubArray{Int16,2,Array{Int16,2},Tuple{UnitRange{Int64},UnitRange{Int64}},false}, ::ImageView.ImageContrast.ContrastSettings, ::ImageView.##41#50) at /home/slava/.julia/v0.5/ImageView/src/contrast.jl:84
 in contrastgui(::SubArray{Int16,2,Array{Int16,2},Tuple{UnitRange{Int64},UnitRange{Int64}},false}, ::ImageView.ImageContrast.ContrastSettings, ::Function) at /home/slava/.julia/v0.5/ImageView/src/contrast.jl:27
 in (::ImageView.##40#49)(::String) at /home/slava/.julia/v0.5/ImageView/src/display.jl:307
 in jl_tcl_callback(::Ptr{Void}, ::Ptr{Void}, ::Int32, ::Ptr{Ptr{UInt8}}) at /home/slava/.julia/v0.5/Tk/src/tkwidget.jl:147
 in tcl_doevent(::Timer, ::Int64) at /home/slava/.julia/v0.5/Tk/src/tkwidget.jl:20
 in (::Base.##349#350{Tk.#tcl_doevent,Timer})() at ./event.jl:38


meanwhile 
```
x=rand(UInt16,128,128)
imshow(x)
```
with further running contrast gui is OK.

**Comment by postoroniy** [comment]
on "big" and even gray images contrast is very slow while moving control to increase contrast
and when click close gui  I got this
error during Tk callback: 
ERROR: Tk.TclError("invalid command name \".jl_win38.jl_ttk_frame39.jl_ttk_scale42\"")
 in tcl_eval(::String, ::Ptr{Void}) at /home/slava/.julia/v0.5/Tk/src/tkwidget.jl:97
 in #tcl#43(::Array{Any,1}, ::Function, ::Tk.Tk_Scale, ::Vararg{Any,N}) at /home/slava/.julia/v0.5/Tk/src/core.jl:48
 in cget(::Tk.Tk_Scale, ::String, ::Void) at /home/slava/.julia/v0.5/Tk/src/core.jl:88
 in set_value(::Tk.Tk_Scale, ::Float32) at /home/slava/.julia/v0.5/Tk/src/widgets.jl:261
 in (::ImageView.ImageContrast.##4#12{ImageView.ImageContrast.ContrastSettings})(::String) at /home/slava/.julia/v0.5/ImageView/src/contrast.jl:174
 in (::Tk.##97#98{ImageView.ImageContrast.##4#12{ImageView.ImageContrast.ContrastSettings}})(::String, ::String, ::Vararg{String,N}) at /home/slava/.julia/v0.5/Tk/src/widgets.jl:268
 in jl_tcl_callback(::Ptr{Void}, ::Ptr{Void}, ::Int32, ::Ptr{Ptr{UInt8}}) at /home/slava/.julia/v0.5/Tk/src/tkwidget.jl:147
 in tcl_doevent(::Timer, ::Int64) at /home/slava/.julia/v0.5/Tk/src/tkwidget.jl:20
 in (::Base.##349#350{Tk.#tcl_doevent,Timer})() at ./event.jl:384

**Comment by timholy** [comment]
Hah, that error with `Int16` rather than `UInt16` turned out to be due to integer overflow,
```julia
julia> typemax(Int16) - typemin(Int16)
-1
```
That's fixed in my recent commit.

I observed the slowness too. It seems to be a Winston or Tk problem: put println statements before and after [this block](https://github.com/timholy/ImageView.jl/blob/a3624638f210216a2b69bab8a5dff221a3c76cae/src/contrast.jl#L94-L97) and you'll see it's very slow in the drawing phase. I don't have time to debug that, might need you to jump in on that one. (Was it slow before the Images 0.6.0 merge?)

**Comment by postoroniy** [comment]
that was bit faster now it's nearly frozen

**Comment by postoroniy** [comment]
ok, will try to fix slowness

**Comment by timholy** [comment]
I just profiled, and it seems to be spending all its time in Cairo's text rendering.

**Comment by postoroniy** [comment]
well, I noticed that text  below(where should be scale) on contrast gui when you have signed int
looks broken

**Comment by postoroniy** [comment]
when uint16
screenshot from 2017-01-31 15 01 16

**Comment by timholy** [comment]
Are you sure that's my problem? Winston is generating the graph. Your best bet would be to steal code from ImageView and make a reduced test case.

**Pull request merged**
