### PR TITLE
RFC: Adapt Timer code to v0.4 changes (don't merge yet)

### PR DESCRIPTION
**Pull request by kmsquire**
* depends on Compat for older Julia versions

This PR should only be merged after https://github.com/JuliaLang/Compat.jl/pull/103 is merged and a new Compat is tagged.

@timholy, these changes should be correct, but I don't have a good way to test them.

### CODE REVIEW

**Comment by kmsquire** [comment]
@timholy, this should be ready to go, but is untested.  Do you know of any publicly available 3D or 4D images in that can be used to test the timer code?

**Comment by timholy** [comment]
There's [this one](https://github.com/timholy/ImageView.jl/blob/master/test/test4d.jl), which synthesizes a 4D image.

**Comment by timholy** [comment]
(Meaning, if you locally say `include("runtests.jl")`, you can play with it and see if everything works.)

**Comment by kmsquire** [comment]
Heh. I should look more carefully at the tests! ;-). I'll check it out.

**Comment by timholy** [comment]
There was a small problem fixed in 4cb34f87f50d8918c300a3396239fa813f9d2033, otherwise this was great. Thanks!

**Pull request merged**
